# Change these first
owner: chrisbergeron # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Chris Bergero'n Tech Blog
    url: https://chrisbergeron.com
  - name: The Holding Company
    url: https://holdingco.com
  - name: MΞTΛcrypt
    url: metacrypt.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /
  logoUrl: https://chrisbergeron.com/logo.png
  name: Chris Bergeron's Blog
  #cname: status.chrisbergeron.com
  introTitle: "**Uptime Status** of Chris Bergeron's Tech Blog"
  introMessage: This is a status page which uses **real-time** data from my [GitHub repository](https://github.com/chrisbergeron/upptime). Serverless - just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)

  theme: dark
  favicon: https://chrisbergeron.com/favicon.ico
  navbar:
#    - title: Status
#      href: https://status.chrisbergeron.com
    - title: Chris Bergeron Tech Blog
      href: https://chrisbergeron.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
